### ISSUE TITLE
Trouble installing using pip

### ISSUE THREAD

**Issue by MollieBakal** [mozilla/pyo3-parsepatch#32]
When trying to install using "pip3 install rs-parsepatch" on a Mac, I run into an issue where lock_api will not compile, and so the entire install fails. 
Collecting rs-parsepatch
  Using cached rs_parsepatch-0.3.3.tar.gz (115 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: rs-parsepatch
  Building wheel for rs-parsepatch (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.8/bin/python3.8 /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpwb7ioe_v
       cwd: /private/tmp/pip-install-ixn5_0am/rs-parsepatch
  Complete output (30 lines):
     Compiling proc-macro2 v1.0.24
     Compiling unicode-xid v0.2.1
     Compiling syn v1.0.48
     Compiling proc-macro-hack v0.5.19
     Compiling serde_derive v1.0.117
     Compiling serde v1.0.117
     Compiling ryu v1.0.5
     Compiling serde_json v1.0.59
     Compiling cfg-if v0.1.10
     Compiling libc v0.2.80
     Compiling itoa v0.4.6
     Compiling regex-syntax v0.6.21
     Compiling autocfg v1.0.1
     Compiling smallvec v1.4.2
     Compiling version_check v0.9.2
     Compiling log v0.4.11
     Compiling inventory v0.1.9
     Compiling scopeguard v1.1.0
     Compiling unindent v0.1.7
     Compiling lock_api v0.3.4
  error: could not compile `lock_api`.
  
  To learn more, run the command again with --verbose.
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  💥 maturin failed
    Caused by: Failed to build a native library through cargo
    Caused by: Cargo build finished with "exit code: 101": `cargo rustc --message-format json --manifest-path Cargo.toml --lib --release -- -C link-arg=-undefined -C link-arg=dynamic_lookup`
  Running `maturin pep517 build-wheel -i python`
  Error: Command '['maturin', 'pep517', 'build-wheel', '-i', 'python']' returned non-zero exit status 1.

**Comment by marco-c** [comment]
It looks like it is failing while compiling https://github.com/mozilla/rust-parsepatch. Can you try to clone that repo directly and compile it?

We should also offer Mac wheels.

**Comment by MollieBakal** [comment]
Using "cargo build", which I believe is the compile, I got only the following output:
   Compiling log v0.4.11
   Compiling cfg-if v0.1.10
   Compiling parsepatch v0.2.8 (/Users/{}/Downloads/rust-parsepatch-master)
    Finished dev [unoptimized + debuginfo] target(s) in 2.91s

Didn't even need to compile the lock_api. Was that the wrong command? "cargo run" produces "error: a bin target must be available for `cargo run`"

**Comment by marco-c** [comment]
What if you clone this repo instead and try to `cargo build` it?

**Comment by calixteman** [comment]
I uploaded packages for python 3.8 and 3.9 .
Anyway, the way to build is pretty easy:
```
rustup update
cargo install maturin
maturin build -i python3.9 --no-sdist
```

**Comment by MollieBakal** [comment]
There we go. Just reproduced the error building pyo3-parsepatch (the rust-parsepatch wouldn't build with that command?). The extended error message is as follows:
`   Compiling lock_api v0.3.4
error[E0554]: `#![feature]` may not be used on the stable release channel25/61: version_check, regex-syntax, lock_...
  --> /Users/MollieBakal/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.3.4/src/lib.rs:91:34
   |
91 | #![cfg_attr(feature = "nightly", feature(const_fn))]
   |                                  ^^^^^^^^^^^^^^^^^


   Compiling num-traits v0.2.14
error: aborting due to previous error==>                               ] 28/61: num-traits(build.rs), regex-syntax...


For more information about this error, try `rustc --explain E0554`.    ] 28/61: num-traits(build.rs), regex-syntax...

error: could not compile `lock_api`.
`

**Comment by MollieBakal** [comment]
There we go. Just reproduced the error building pyo3-parsepatch (the rust-parsepatch wouldn't build with that command?). The extended error message is as follows:
Compiling lock_api v0.3.4 error[E0554]: \#![feature]` may not be used on the stable release channel25/61: version_check, regex-syntax, lock_...
--> /Users/{}/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.3.4/src/lib.rs:91:34
|
91 | #![cfg_attr(feature = "nightly", feature(const_fn))]
| ^^^^^^^^^^^^^^^^^

Compiling num-traits v0.2.14
error: aborting due to previous error==> ] 28/61: num-traits(build.rs), regex-syntax...

For more information about this error, try `rustc --explain E0554`. ] 28/61: num-traits(build.rs), regex-syntax...

error: could not compile `lock_api`.
`

**Comment by calixteman** [comment]
Try to switch to nightly: `rustup default nightly`

**Comment by MollieBakal** [comment]
So part of my issue might be that I installed rust through homebrew, not rustup (for some reason, that meant bash didn't understand the rustup command). Uninstalled that, reinstalled through rustup, still crashed on lock_api on the stable release, but compiles on the nightly with the following.

warning: the feature `specialization` is incomplete and may not be safe to use and/or cause compiler crashes
 --> src/lib.rs:1:12
  |
1 | #![feature(specialization)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default
  = note: see issue #31844 <https://github.com/rust-lang/rust/issues/31844> for more information
  = help: consider using `min_specialization` instead, which is more stable and complete


    Building warning: 1 warning emitted

**Comment by MollieBakal** [comment]
That seems to have resolved the original issue with rs-parsepatch, thank you.

**Comment by marco-c** [comment]
With #31, we wouldn't need nightly anymore.
